### ISSUE TITLE
How to prevent grouping of similar queries into one query with 'xxx' value ?

### ISSUE THREAD

**Issue by irbux** [steventen/sql_tracker#1]
Hi Steven, thank you  for the good staff.
Currently  I have  error  related with replacing value, it's happening  during rails app works:
`ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "xxx" does not exist
LINE 1: ...ELECT "users".* FROM "users" WHERE "users"."id" = xxx LIMIT ...`

I think if prevent replacing value all will work fine.

**Comment by steventen** [comment]
Hi @KeiserSoze thanks for the reporting! 

Can you tell me a bit more about when it happens?

I'm wondering if it happens because the payload data from Rails' instrumentation API is shared across the application. I made a commit 1ef9577cb8eab982d62cf2514ee3f0ee1a3287d6 to try to solve this issue. Can you use the latest commit in your app and see if it solves the problem?

Thanks

**Comment by irbux** [comment]
Hello ! 
I've didn't tested your commit, yet. But I can tell when it is happening.
During initialize current_user  just after start server.
I have two controllers (sorry but I can't show code here ), first controller it's SessionsCtrl which takes  from front-end  authtoken and pass it to the auth class , auth class decode token and try to find user by the information from the token, so during this  sql query  process  I get a error.
Thank thank you for the commit . I will test and give you result.

**Comment by irbux** [comment]
Thanks, with  commit 1ef9577 works fine.
